version: '3.5'

services:
  #  postgres:
  #    image: mdillon/postgis
  #    restart: always
  #    environment:
  #      POSTGRES_USER: mika
  #      POSTGRES_PASSWORD: mika
  #    volumes:
  #      - ./store/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  #    networks:
  #      - mika_testing
  #
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mika
      MYSQL_DATABASE: mika
    volumes:
      - ./docker/mysql_init.sql:/docker-entrypoint-initdb.d/00_mysql_init.sql
      - ./store/mysql/schema.sql:/docker-entrypoint-initdb.d/10_schema.sql
    ports:
      - 3306:3306
    networks:
      bri

  redis:
    image: redis:6-alpine
    restart: always

  mika:
    build:
      dockerfile: docker/dev.Dockerfile
      context: "."
    restart: "no"
    depends_on:
      - mysql
    volumes:
      - geo_data:/app/geo_data
      - ./docker/mika.yaml:/app/mika.yaml

volumes:
  geo_data:
