version: '3.5'

services:
  mysql:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mika
      MYSQL_DATABASE: mika
    volumes:
      - ./docker/mysql_init.sql:/docker-entrypoint-initdb.d/00_mysql_init.sql
      - ./store/mysql/schema.sql:/docker-entrypoint-initdb.d/10_schema.sql
    networks:
      - mika_test

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - mika_test

  mika:
    build:
      dockerfile: docker/test.Dockerfile
      context: "."
    restart: always
    depends_on:
      - redis
      - mysql
    volumes:
      - geo_data:/app/geo_data
      - ./docker/mika_testing_mysql.yaml:/app/mika.yaml
    networks:
      - mika_test
    command: "make test"

volumes:
  geo_data:

networks:
  mika_test:
    driver: bridge